
engineering_branches = [
    {"sl_no": 1, "name": "Aeronautical Engineering", "code": "AE"},
    {"sl_no": 2, "name": "Aerospace Engineering", "code": "AS"},
    {"sl_no": 3, "name": "Agriculture Engineering", "code": "AL"},
    {"sl_no": 4, "name": "Agricultural Engineering", "code": "AG"},
    {"sl_no": 5, "name": "Artificial Intelligence & Data Science", "code": "AD"},
    {"sl_no": 6, "name": "Artificial Intelligence & Machine Learning", "code": "AI"},
    {"sl_no": 7, "name": "Automation & Robotics Engineering", "code": "AR"},
    {"sl_no": 8, "name": "Automobile Engineering", "code": "AU"},
    {"sl_no": 9, "name": "Automotive Engineering", "code": "AVE"},
    {"sl_no": 10, "name": "Bachelor of Design", "code": "BD"},
    {"sl_no": 11, "name": "Bachelor of Urban & Regional Planning", "code": "BP"},
    {"sl_no": 12, "name": "Bachelor of Planning", "code": "BPL"},
    {"sl_no": 13, "name": "Bachelor of Design (Fashion Design)", "code": "BFD"},
    {"sl_no": 14, "name": "Bachelor of Design (Industrial Design)", "code": "BID"},
    {"sl_no": 15, "name": "Bachelor of Design (Lifestyle & Accessory Design)", "code": "BLD"},
    {"sl_no": 16, "name": "Bachelor of Design (Communication & Design)", "code": "BDC"},
    {"sl_no": 17, "name": "Bio Electronics Engineering", "code": "BEE"},
    {"sl_no": 18, "name": "Bio Medical Engineering", "code": "BM"},
    {"sl_no": 19, "name": "Biotechnology", "code": "BT"},
    {"sl_no": 20, "name": "Ceramic And Cement Technology", "code": "CC"},
    {"sl_no": 21, "name": "Chemical Engineering", "code": "CH"},
    {"sl_no": 22, "name": "Civil (Construction Engineering & Management)", "code": "CVC"},
    {"sl_no": 23, "name": "Civil Construction & Sustainability Engineering", "code": "CCS"},
    {"sl_no": 24, "name": "Civil Engineering", "code": "CV"},
    {"sl_no": 25, "name": "Civil Engineering (Kannada)", "code": "CK"},
    {"sl_no": 26, "name": "Civil Engineering (SC)", "code": "CVS"},
    {"sl_no": 27, "name": "Civil Engineering with Computer Application", "code": "CCA"},
    {"sl_no": 28, "name": "Computer & Communication Engineering", "code": "CM"},
    {"sl_no": 29, "name": "Computer Engineering", "code": "CE"},
    {"sl_no": 30, "name": "Computer Science", "code": "CR"},
    {"sl_no": 31, "name": "Computer Science & Business Systems", "code": "CB"},
    {"sl_no": 32, "name": "Computer Science & Design", "code": "CG"},
    {"sl_no": 33, "name": "Computer Science & Engineering", "code": "CS"},
    {"sl_no": 34, "name": "Computer Science & Engineering (AI & ML)", "code": "CI"},
    {"sl_no": 35, "name": "Computer Science & Engineering (AI)", "code": "CA"},
    {"sl_no": 36, "name": "Computer Science & Engineering (Block Chain)", "code": "CSB"},
    {"sl_no": 37, "name": "Computer Science & Engineering (Cyber Security)", "code": "CY"},
    {"sl_no": 38, "name": "Computer Science & Engineering (Data Science)", "code": "CD"},
    {"sl_no": 39, "name": "Computer Science & Engineering (IOT & Cyber Security Incl. Block Chain)", "code": "IC"},
    {"sl_no": 40, "name": "Computer Science & Engineering (IOT)", "code": "CO"},
    {"sl_no": 41, "name": "Computer Science & Engineering (Networks)", "code": "CNW"},
    {"sl_no": 42, "name": "Computer Science & Engineering (SC)", "code": "CSS"},
    {"sl_no": 43, "name": "Computer Science & Information Technology", "code": "CIT"},
    {"sl_no": 44, "name": "Computer Science & Technology", "code": "CN"},
    {"sl_no": 45, "name": "Computer Science & Technology (Big Data)", "code": "CBD"},
    {"sl_no": 46, "name": "Computer Science & Technology (DevOps)", "code": "CSD"},
    {"sl_no": 47, "name": "Construction Technology & Management", "code": "CT"},
    {"sl_no": 48, "name": "Cyber Security", "code": "CX"},
    {"sl_no": 49, "name": "Data Science", "code": "DS"},
    {"sl_no": 50, "name": "Electrical & Computer Engineering", "code": "ECE"},
    {"sl_no": 51, "name": "Electrical & Electronics Engineering", "code": "EE"},
    {"sl_no": 52, "name": "Electronics & Communication (Industry Integrated)", "code": "EII"},
    {"sl_no": 53, "name": "Electronics & Communication Engineering", "code": "EC"},
    {"sl_no": 54, "name": "Electronics & Communication Engineering (SC)", "code": "ECS"},
    {"sl_no": 55, "name": "Electronics & Computer Engineering", "code": "UE"},
    {"sl_no": 56, "name": "Electronics & Computer Science", "code": "ES"},
    {"sl_no": 57, "name": "Electronics & Instrumentation Engineering", "code": "EI"},
    {"sl_no": 58, "name": "Electronics & Telecommunication Engineering", "code": "ET"},
    {"sl_no": 59, "name": "Electronics Engg. (VLSI Design & Technology)", "code": "VL"},
    {"sl_no": 60, "name": "Electronics & Communication Engineering (VLSI Design & Technology)", "code": "ECV"},
    {"sl_no": 61, "name": "Energy Engineering", "code": "EN"},
    {"sl_no": 62, "name": "Industrial & Production Engineering", "code": "IP"},
    {"sl_no": 63, "name": "Industrial Engineering & Management", "code": "IM"},
    {"sl_no": 64, "name": "Information Science & Engineering", "code": "IS"},
    {"sl_no": 65, "name": "Information Science & Technology", "code": "IST"},
    {"sl_no": 66, "name": "Information Technology", "code": "INT"},
    {"sl_no": 67, "name": "Information Technology (AR / VR)", "code": "IAR"},
    {"sl_no": 68, "name": "Information Technology (Data Analytics)", "code": "IDA"},
    {"sl_no": 69, "name": "Instrumentation Technology", "code": "IT"},
    {"sl_no": 70, "name": "Marine Engineering", "code": "MR"},
    {"sl_no": 71, "name": "Mathematics & Computing", "code": "MAC"},
    {"sl_no": 72, "name": "Mechanical & Aerospace Engineering", "code": "MAE"},
    {"sl_no": 73, "name": "Mechanical Engineering", "code": "ME"},
    {"sl_no": 74, "name": "Mechanical Engineering (SC)", "code": "MES"},
    {"sl_no": 75, "name": "Mechatronics Engineering", "code": "MT"},
    {"sl_no": 76, "name": "Medical Electronics Engineering", "code": "MD"},
    {"sl_no": 77, "name": "Mining Engineering", "code": "MI"},
    {"sl_no": 78, "name": "Nano Technology", "code": "NT"},
    {"sl_no": 79, "name": "Petroleum Engineering", "code": "PTE"},
    {"sl_no": 80, "name": "Robotics", "code": "ROB"},
    {"sl_no": 81, "name": "Robotics & Artificial Intelligence", "code": "RI"},
    {"sl_no": 82, "name": "Robotics & Automation", "code": "RA"},
    {"sl_no": 83, "name": "Robotics & Mechatronics", "code": "ROM"},
    {"sl_no": 84, "name": "Smart Agritech", "code": "SA"},
    {"sl_no": 85, "name": "Telecommunication Engineering", "code": "TE"},
    {"sl_no": 86, "name": "Textile Technology", "code": "TX"},
    {"sl_no": 87, "name": "VLSI", "code": "VLS"},
    {"sl_no": 88, "name": "Computer Science & Engineering (Artificial Intelligence & Data Science)", "code": "CAD"}
]

architecture_branches = [
    {"sl_no": 1, "name": "Bachelor of Architecture (B.Arch)", "code": "AT"},
    {"sl_no": 2, "name": "Bachelor of Urban & Regional Planning", "code": "BP"},
    {"sl_no": 3, "name": "Bachelor of Design", "code": "BD"},
    {"sl_no": 4, "name": "Bachelor of Design (Fashion Design)", "code": "BFD"},
    {"sl_no": 5, "name": "Bachelor of Design (Industrial Design)", "code": "BID"},
    {"sl_no": 6, "name": "Bachelor of Design (Lifestyle & Accessory Design)", "code": "BLD"},
    {"sl_no": 7, "name": "Bachelor of Design (Communication & Design)", "code": "BDC"},
    {"sl_no": 8, "name": "Bachelor of Planning", "code": "BPL"},
    {"sl_no": 9, "name": "B. Design (Interior Design)", "code": "BIN"}
]
