colleges_list = [{'code': 'E001',
  'name': 'Acharya Institute of Technology- Soladevanahalli, Bengaluru',
  'location': 'BENGALURU',
  'about': 'Acharya Institute of Technology (AIT) is an engineering college in Bangalore, India, established in 2000. '
           'It is affiliated with Visvesvaraya Technological University (VTU) and accredited by the National Board of '
           'Accreditation (NBA) and NAAC. The college offers a wide range of undergraduate and postgraduate programs '
           'in engineering and technology.',
  'website': 'https://www.ait.ac.in/'},
 {'code': 'E003',
  'name': 'A.C.S. College of Engineering Kambipura -(Mysore Road), Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.acsce.edu.in/'},
 {'code': 'E004',
  'name': 'Adichunchanagiri Institute Of Technology-Jyothi Nagara, Chikkamagaluru',
  'location': 'CHIKAMAGALURU',
  'website': 'https://aitckm.edu.in/'},
 {'code': 'E005',
  'name': 'Akash Institute of Engineering and Technology-Devanahalli, Bengaluru Rural',
  'location': 'BENGALURU RURAL',
  'website': 'https://www.akashiet.com/'},
 {'code': 'E006',
  'name': "Alva's Institute of Engineering & Technology-Moodbidri, Mangaluru",
  'location': 'MANGALURU',
  'website': 'https://www.aiet.org.in/'},
 {'code': 'E007',
  'name': 'AMC Engineering College-Bannerghatta Rd, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://amcgroup.edu.in/amcec'},
 {'code': 'E009',
  'name': 'Angadi Institute of Technology and Management-Savagaon Road, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://www.aitmbgm.ac.in/'},
 {'code': 'E010',
  'name': 'Allum Institute of Technology and Management-Bellary',
  'location': 'BALLARI',
  'website': 'https://www.allumit.com'},
 {'code': 'E011',
  'name': 'APS College of Engineering-Kanakapura Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.apsce.ac.in'},
 {'code': 'E012',
  'name': 'Atria Institute of Technology-Hebbal, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://atria.edu'},
 {'code': 'E013',
  'name': 'Akshaya Institute of Technology-Koratagere Road, Tumakuru',
  'location': 'TUMAKURU',
  'website': 'https://www.akshaya.edu.in'},
 {'code': 'E014',
  'name': 'Anuvartik Mirji Bharatesh Institute of Technology-Shindholli Cross, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://www.ambit.edu.in'},
 {'code': 'E015',
  'name': 'B.N.M. Institute of Technology-Banashankari, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.bnmit.org'},
 {'code': 'E016',
  'name': 'KLE Technological University (Formerly known as BVBCET)-Vidyanagar, Hubbali',
  'location': 'HUBBALLI',
  'website': 'https://www.kletech.ac.in'},
 {'code': 'E017',
  'name': 'Ballari Institute of Technology & Management-Near Allipura, Ballari',
  'location': 'BALLARI',
  'website': 'https://www.bitm.edu.in'},
 {'code': 'E019',
  'name': 'Bangalore Institute of Technology-V V Puram, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://bit-bangalore.edu.in'},
 {'code': 'E020',
  'name': 'Bangalore Technological Institute-Chikkanayakanahalli Dinne, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.btibangalore.org'},
 {'code': 'E021',
  'name': 'Bapuji Institute of Engineering & Technology- Shamanur Road, Davangere',
  'location': 'DAVANGERE',
  'website': 'https://bietdvg.edu'},
 {'code': 'E023',
  'name': 'Basavakalyan Engineering College-NH9 Basavakalyan, Bidar',
  'location': 'BIDAR',
  'website': 'https://www.becbgk.edu.in'},
 {'code': 'E024',
  'name': 'Basaveshwar Engineering College-Vidyanagar, Bagalkot',
  'location': 'BAGALKOT',
  'website': 'https://www.becbgk.edu'},
 {'code': 'E026',
  'name': "BLDEA's V.P. Dr. P.G. Halakatti College of Engineering & Technology,Ashram Road, Vijayapura",
  'location': 'VIJAYAPURA',
  'website': 'https://www.bldeacet.ac.in'},
 {'code': 'E027',
  'name': 'BMS College of Engineering-Basavanagudi, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.bmsce.ac.in'},
 {'code': 'E028',
  'name': 'BMS Institute of Technology & Management-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.bmsit.ac.in'},
 {'code': 'E030',
  'name': 'Brindavan College of Engineering-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.brindavancollege.edu.in'},
 {'code': 'E032',
  'name': 'C.M.R. Institute of Technology-Brookefield, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.cmrit.ac.in'},
 {'code': 'E033',
  'name': 'Cambridge Institute of Technology, K R Puram, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.cambridge.edu.in'},
 {'code': 'E035',
  'name': 'Channabasaveshwara Institute of Technology-Gubbi, Tumakuru',
  'location': 'TUMAKURU',
  'website': 'https://www.cittumkur.org'},
 {'code': 'E036',
  'name': 'Chanakya University-Devanahalli,Bengaluru Rural',
  'location': 'BENGALURU RURAL',
  'website': 'https://chanakyauniversity.edu.in'},
 {'code': 'E037',
  'name': 'City Engineering College-Doddakalasandra, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.cityengineeringcollege.ac.in'},
 {'code': 'E038',
  'name': 'Coorg Institute of Technology-Ponnampet, South Kodagu',
  'location': 'SOUTH KODAGU',
  'website': 'https://www.coorginstituteoftechnology.com'},
 {'code': 'E039',
  'name': 'Dayananda Sagar Academy of Technology & Management-Kanakapura Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://dsatm.edu.in'},
 {'code': 'E040',
  'name': 'Dayananda Sagar College of Engineering-Kumaraswamy Layout, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.dsce.edu.in'},
 {'code': 'E041',
  'name': 'DON BOSCO Institute of Technology-Kumbalgodu, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.dbit.co.in'},
 {'code': 'E042',
  'name': 'Dr. Ambedkar Institute of Technology-Malathahalli, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.drait.edu.in'},
 {'code': 'E043',
  'name': 'Yenepoya Institute of Technology (formerly known as Dr. M V Shetty Institute of Technology)-Moodbidri, '
          'Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://engg.yenepoya.edu.in'},
 {'code': 'E044',
  'name': 'Dr.Shri Shri Shivakumara Mahaswamy College of Engineering-Nelamangala, Bengaluru Rural',
  'location': 'BENGALURU RURAL',
  'website': 'https://www.ssit.edu.in'},
 {'code': 'E045',
  'name': 'Dr H N National College Of Engineering - Jayanagar Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.hnnce.ac.in'},
 {'code': 'E046',
  'name': 'East Point College of Engineering and Technology-Avalahalli, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://eastpoint.ac.in'},
 {'code': 'E048',
  'name': 'East West Institute of Technology-BEL Layout, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.ewit.edu.in'},
 {'code': 'E049',
  'name': 'Garden City University-Old Madras Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.gardencity.university'},
 {'code': 'E050',
  'name': 'Global Academy of Technology-Rajarajeshwari Nagar, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.gat.ac.in'},
 {'code': 'E051',
  'name': 'GM Institute of Technology-P B Road, Davangere',
  'location': 'DAVANGERE',
  'website': 'https://gmit.ac.in/'},
 {'code': 'E053',
  'name': 'Gopalan College of Engineering And Management- Whitefield, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.gopalancolleges.com/gcem/'},
 {'code': 'E055',
  'name': 'GSSS Institute of Engineering and Technology for Women-Metagalli, Mysuru',
  'location': 'MYSURU',
  'website': 'https://geethashishu.in/'},
 {'code': 'E056',
  'name': "H.K.E.Society's P.D.A. College of Engineering-Aiwan E Shahi area, Kalaburgi",
  'location': 'KALABURGI',
  'website': 'https://www.pdacek.ac.in'},
 {'code': 'E058',
  'name': 'Sri Jayachamarajendra College of Engineering (constituent college of JSS Science and Technology '
          'University)-Manasagangothri, Mysuru',
  'location': 'MYSURU',
  'website': 'https://www.jssstuniv.in/'},
 {'code': 'E059',
  'name': 'Jawaharlal Nehru New College of Engineering (JNNCE)-Swalanga Road, Shivamogga',
  'location': 'SHIVAMOGGA',
  'website': 'https://jnnce.ac.in/'},
 {'code': 'E060',
  'name': 'JSS Academy of Technical Education-Kengeri Main Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://jssateb.ac.in/'},
 {'code': 'E061',
  'name': 'JSS Science & Technology University-Mysuru',
  'location': 'MYSURU',
  'website': 'https://www.jssstuniv.in/'},
 {'code': 'E062',
  'name': 'Jain College of Engineering-T.S Nagar, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://jainbgm.in/'},
 {'code': 'E063',
  'name': 'Jnana Vikas Institute of Technology-Bidadi, Ramnagar Taluk, Bengaluru Rural',
  'location': 'BENGALURU RURAL',
  'website': 'https://www.jvit.edu.in'},
 {'code': 'E064',
  'name': 'Jain College Of Engineering & Research-Udyambag, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://www.jcer.in'},
 {'code': 'E065',
  'name': 'KLE Technological University (Formerly called as KLE Dr. M.S. sheshgiri college of Engineering and '
          'Technology)-Udyambag, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://www.kleuniversity.edu.in'},
 {'code': 'E066',
  'name': 'KLE College of Engineering and Technology, Chikodi Dist., Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://www.klecet.edu.in'},
 {'code': 'E067',
  'name': 'K.S School of Engineering And Management-Off Kanakapura Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://kssem.edu.in/'},
 {'code': 'E068',
  'name': 'K.S. Institute of Technology-Kanakapura Main Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://ksit.ac.in/'},
 {'code': 'E069',
  'name': 'KVG College Of Engineering-Sullia, Dakshina Kannada',
  'location': 'DAKSHINA KANNADA',
  'website': 'https://kvgengg.com/'},
 {'code': 'E070',
  'name': 'Kalpataru Institute of Technology-B H Road, Tiptur',
  'location': 'TIPTUR',
  'website': 'https://www.kittiptur.ac.in/'},
 {'code': 'E071',
  'name': 'Karavali Institute of Technology-Kottara, Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://www.karavaliinstituteoftechnology.com'},
 {'code': 'E073',
  'name': 'KLS Gogte Institute of Technology-Udyambag, Belagavi',
  'location': 'BELAGAVI',
  'website': 'https://git.edu/'},
 {'code': 'E074',
  'name': "KLS's. Vishwanathrao Deshpande Institute of Technology-Dandeli Road, Haliyal",
  'location': 'HALIYAL',
  'website': 'https://klsvdit.edu.in/'},
 {'code': 'E075',
  'name': 'K. N. S. INSTITUTE OF TECHNOLOGY-Yelahanka,Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.knsit.com'},
 {'code': 'E076',
  'name': 'M.S. Engineering College-Sadahalli, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.msec.ac.in/'},
 {'code': 'E077',
  'name': 'M.S. Ramaiah Institute of Technology-MSR Nagar, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.msrit.edu/'},
 {'code': 'E078',
  'name': 'Maharaja Institute of Technology-Belawadi, Mandya',
  'location': 'MANDYA',
  'website': 'https://mitmysoresite.wordpress.com/ (or MIT Mandya site)'},
 {'code': 'E079',
  'name': 'Malnad College of Engineering-Rangoli Halla, Hassan',
  'location': 'HASSAN',
  'website': 'https://www.mcehassan.ac.in/'},
 {'code': 'E080',
  'name': 'Mangalore Institute of Technology & Engineering-Moodbidri, Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://www.mite.ac.in/'},
 {'code': 'E081',
  'name': 'Moodalakatte Institute of Technology-Moodalakatte, Kundapura',
  'location': 'KUNDAPURA',
  'website': 'https://www.mitkundapura.com/'},
 {'code': 'E082',
  'name': 'Maharaja Institute of Technology-Thandavapura, Mysuru',
  'location': 'MYSURU',
  'website': 'https://mitmysore.in/'},
 {'code': 'E083',
  'name': 'Mysuru Royal Institute of Technology-Palahallli, Mandya District',
  'location': 'MANDYA',
  'website': 'https://mrit.edu.in/'},
 {'code': 'E084',
  'name': 'Nagarjuna College of Engineering & Technology-Devanahalli Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.nagarjunaeducation.com/'},
 {'code': 'E085',
  'name': 'The National Institute of Engineering, North Campus-Koorgalli, Mysuru',
  'location': 'MYSURU',
  'website': 'https://nie.ac.in'},
 {'code': 'E088',
  'name': 'Navodaya Institute of Technology-Bijangera, Raichur',
  'location': 'RAICHUR',
  'website': 'https://navodaya.edu.in/'},
 {'code': 'E089',
  'name': 'P.E.S.College of Engineering-PES College Road, Mandya',
  'location': 'MANDYA',
  'website': 'https://pesce.ac.in/'},
 {'code': 'E090',
  'name': 'PES Institute of Technology & Management, Shivamogga',
  'location': 'SHIVAMOGGA',
  'website': 'https://pesitm.edu.in/'},
 {'code': 'E094',
  'name': 'Proudhadevaraya Institute of Technology-TB Dam Road, Hosapete',
  'location': 'HOSAPETE',
  'website': 'https://pdit.ac.in/'},
 {'code': 'E095',
  'name': 'R V College of Engineering-Mysore Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.rvce.edu.in'},
 {'code': 'E096',
  'name': 'R.L. Jalappa Institute of Technology-Kodigehalli, Doddaballapur',
  'location': 'DODDABALLAPUR',
  'website': 'https://rljit.in/'},
 {'code': 'E097',
  'name': 'R.R. Institute of Technology-Chikkabanavara, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://rrinstitutions.com/'},
 {'code': 'E098',
  'name': "R.T.E. Society's Rural Engineering College-Hulkoti, Gadag",
  'location': 'GADAG',
  'website': 'https://www.rechulkoti.edu.in/'},
 {'code': 'E099',
  'name': 'Raja Rajeswari College of Engineering-Kumbalgodu, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://rrce.org/'},
 {'code': 'E100',
  'name': 'Rajeev Institute of Technology-BM Bypass Road, Hassan',
  'location': 'HASSAN',
  'website': 'https://www.rajeevit.in/'},
 {'code': 'E101',
  'name': 'Rajiv Gandhi Institute of Technology, R T Nagar Post, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://rgit.ac.in/'},
 {'code': 'E102',
  'name': 'Rao Bahadur Y Mahabaleswarappa Engineering College-Cantonment, Ballari',
  'location': 'Ballari',
  'website': 'https://www.rymec.ac.in/'},
 {'code': 'E104',
  'name': 'RNS Institute of Technology-R R Nagar Post, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.rnsit.ac.in/'},
 {'code': 'E105',
  'name': 'Bheemanna Khandre Institute of Technology-Bhalki, Bidar',
  'location': 'BIDAR',
  'website': 'https://bkitbhalki.org/'},
 {'code': 'E107',
  'name': 'SJB Institute of Technology-Kengeri, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://sjbit.edu.in/'},
 {'code': 'E108',
  'name': 'S J C Institute of Technology-BB Road, Chikkaballapur',
  'location': 'CHIKBALLAPUR',
  'website': 'https://www.sjcit.ac.in'},
 {'code': 'E109',
  'name': 'S.E.A. College of Engineering & Technology-K R Puram, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://seacet.edu.in/'},
 {'code': 'E110',
  'name': "SSET's S.G. Balekundri Institute of Technology-Shivabasava Nagar, Belagavi",
  'location': 'BELAGAVI',
  'website': 'https://www.sgbit.edu.in'},
 {'code': 'E111',
  'name': 'Hirasugar Institute of Technology- Nidasoshi,Belagavi',
  'location': 'NIDASOSHI',
  'website': 'https://hsit.ac.in/'},
 {'code': 'E112',
  'name': 'Sahyadri College of Engineering and Management-Adyar, Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://sahyadri.edu.in/'},
 {'code': 'E113',
  'name': 'Sai Vidya Institute of Technology-Rajan Kunte, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://saividya.ac.in/'},
 {'code': 'E114',
  'name': 'Sambhram Institute of Technology-Jalahalli East, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://sambhramit.com/'},
 {'code': 'E116',
  'name': 'SAPTHAGIRI NPS UNIVERSITY- Hesaraghatta Main Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://sapthagiri.edu.in/'},
 {'code': 'E117',
  'name': 'SDM College of Engineering & Technology, (Tulu Minority)-Kalaghatagi , Dharwad',
  'location': 'DHARWAD',
  'website': 'https://sdmcet.ac.in/'},
 {'code': 'E118',
  'name': 'SDM Institute of Technology, (Tulu Minority)-Ujjire, Dakshina Kannada',
  'location': 'DAKSHINA KANNADA',
  'website': 'https://sdmit.in/'},
 {'code': 'E119',
  'name': 'SECAB Institute of Engineering &Technology-Nauraspur-Bagalkot Road, Vijayapura',
  'location': 'VIJAYAPURA',
  'website': 'https://secab.org/'},
 {'code': 'E121',
  'name': 'Sri Sairam College of Engineering-Anekal, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.sairamce.edu.in/'},
 {'code': 'E122',
  'name': 'Shree Devi Institute of Technology-Kenjar, Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://www.sdit.ac.in'},
 {'code': 'E123',
  'name': 'Shri Madhwa Vadiraja Institute of Technology & Management-Bantakal, Udupi',
  'location': 'UDUPI',
  'website': 'https://smitm.ac.in/'},
 {'code': 'E124',
  'name': 'Shridevi Institute of Engineering & Technology-Sira Road, Tumakuru',
  'location': 'TUMAKURU',
  'website': 'https://www.shrideviengineering.org/'},
 {'code': 'E125',
  'name': 'Siddaganga Institute of Technology-B H Road, Tumakuru',
  'location': 'TUMAKURU',
  'website': 'https://www.sit.ac.in'},
 {'code': 'E126',
  'name': 'Sir M.Visvesvaraya Institute of Technology-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.sirmvit.edu/'},
 {'code': 'E127',
  'name': 'S J M Institute of Technology - NH 4 Bye-pass, Chitradurga',
  'location': 'CHITRADURGA',
  'website': 'https://sjmit.ac.in/'},
 {'code': 'E128',
  'name': 'Smt. Kamala and Sri Venkappa M. Agadi College of Engineering & Technology-Laxmeswar, Gadag',
  'location': 'GADAG',
  'website': 'https://agadiengg.org/'},
 {'code': 'E132',
  'name': 'Sri Krishna Institute of Technology-Chikkabanavara, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.skit.org.in/'},
 {'code': 'E136',
  'name': 'Sri Taralabalu Jagadguru Institute of Technology-Haveri Dist., Ranebennur',
  'location': 'RANEBENNUR',
  'website': 'https://www.stjit.edu.in'},
 {'code': 'E137',
  'name': 'Sri Venkateshwara College of Engineering-KIAL Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.svec.ac.in/'},
 {'code': 'E138',
  'name': 'Srinivas Institute of Technology-Hampankatta, Mangaluru',
  'location': 'MANGALURU',
  'website': 'https://www.sitmangalore.in'},
 {'code': 'E141',
  'name': 'T. John Institute of Technology-Bannerghatta Road, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://tjohnit.com/'},
 {'code': 'E142',
  'name': 'The National Institute of Engineering, South Campus-Mananthavady Road, Mysuru',
  'location': 'MYSURU',
  'website': 'https://nie.ac.in'},
 {'code': 'E143',
  'name': 'Tontadarya College of Engineering-Mundaragi Road , Gadag',
  'location': 'GADAG',
  'website': 'https://tcegagad.edu.in/'},
 {'code': 'E144',
  'name': 'Veerappa Nisty Engineering College-Shorapur, Yadgir',
  'location': 'YADGIR',
  'website': 'https://vnec.ac.in/'},
 {'code': 'E145',
  'name': 'Vemana Institute of Technology-Koramangala, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.vemanaIT.edu.in/'},
 {'code': 'E146',
  'name': 'Vidya Vikas Institute of Engineering & Technology-Alnahally, Mysuru',
  'location': 'MYSURU',
  'website': 'https://www.vviet.ac.in'},
 {'code': 'E147',
  'name': 'Vidyavardhaka College of Engineering-Gokulam, Mysuru',
  'location': 'MYSURU',
  'website': 'https://www.vvce.ac.in'},
 {'code': 'E148',
  'name': 'Vivekananda College of Engineering and Technology-Puttur, Dakshina Kannada',
  'location': 'DAKSHINA KANNADA',
  'website': 'https://vcetputtur.ac.in/'},
 {'code': 'E152',
  'name': 'ATME College of Engineering-Bannur Road, Mysuru',
  'location': 'MYSURU',
  'website': 'https://www.atme.in/'},
 {'code': 'E156',
  'name': 'Jyothy Institute of Technology-Tathguni, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://jyothyit.ac.in/'},
 {'code': 'E158',
  'name': 'Shetty Institute of Technology -Shahabad Road,Kalaburagi',
  'location': 'Kalaburagi',
  'website': 'https://sitgulbarga.org/'},
 {'code': 'E159',
  'name': 'Lingaraj Appa Engineering-Gornalli, Bidar',
  'location': 'BIDAR',
  'website': 'https://lingarajappaengg.org/'},
 {'code': 'E161',
  'name': 'Cambridge Institute of Technology (North Campus)-Kundana, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://engg.cambridge.edu.in/'},
 {'code': 'E164',
  'name': 'Reva University-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.reva.edu.in/'},
 {'code': 'E165',
  'name': 'Alliance College of Engineering & Design. Alliance University-Anekal, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.alliance.edu.in/'},
 {'code': 'E171',
  'name': 'GITAM (Deemed to be University)-Doddaballapur taluk, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.gitam.edu'},
 {'code': 'E172',
  'name': 'Mysore College of Engineering and Management-Chikkahalli, Mysuru',
  'location': 'MYSURU',
  'website': 'https://mysorecollegeofengineering.org/'},
 {'code': 'E173',
  'name': 'Presidency University-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://presidencyuniversity.in/'},
 {'code': 'E183',
  'name': 'Jain Institute of Technology-Avaragere Village, Davangere',
  'location': 'DAVANGERE',
  'website': 'https://jainbgm.in/jit-dvg/'},
 {'code': 'E187',
  'name': 'CMR University-Bagalor Chagalatti, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.cmr.edu.in/'},
 {'code': 'E191',
  'name': 'Sir M V School Of Architecture-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.sirmvsa.edu.in/'},
 {'code': 'E194',
  'name': 'Jain College of Engineering and Technology-Unkal, Hubballi',
  'location': 'HUBBALLI',
  'website': 'https://jainbgm.in/jcet-hubli/'},
 {'code': 'E195',
  'name': 'Navkis College of Engineering -Kandali NH75, Hassan',
  'location': 'HASSAN',
  'website': 'https://navkiscollegeofengineering.com/'},
 {'code': 'E197',
  'name': 'M.S. Ramaiah University of Applied Sciences-MSR Nagar, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.msruas.ac.in/'},
 {'code': 'E198',
  'name': 'R V Institute of Technology and Management-J P Nagar, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://www.rvitm.edu.in/'},
 {'code': 'E199',
  'name': 'Biluru Gurubasava Mahaswamiji Institute of Technology-Mudhol, Bagalkot',
  'location': 'BAGALKOT',
  'website': 'https://bgmit.org/'},
 {'code': 'E201',
  'name': 'G Madegowda Institute of Technology-Maddur, Mandya District',
  'location': 'MANDYA',
  'website': 'https://gmitmandya.ac.in/'},
 {'code': 'E202',
  'name': 'C Byregowda Institute of Technology-Thoradevandahalli, Kolar',
  'location': 'KOLAR',
  'website': 'https://cbitkolar.edu.in/'},
 {'code': 'E203',
  'name': 'Amruta Institute of Engineering and Management Science-Bidadi, Ramnagar Taluk, Bengaluru Rural',
  'location': 'BENGALURU RURAL',
  'website': 'https://aiems.edu.in/'},
 {'code': 'E204',
  'name': "H.K.E. Society's Sir M. Visvesvaraya College of Engineering-Yermarus Camp, Raichur",
  'location': 'RAICHUR',
  'website': 'https://hkesmvsce.org/'},
 {'code': 'E205',
  'name': 'Vijaya Vittala Institution of Technology-Kothanur, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://vvit.co.in/'},
 {'code': 'E206',
  'name': 'Cauvery Institute Of Technology-Sundahalli, Mandya',
  'location': 'MANDYA',
  'website': 'https://cauveryit.ac.in/'},
 {'code': 'E207',
  'name': 'BGS College of Engineering and Technology-Mahalaxmipuram, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://bgscet.ac.in/'},
 {'code': 'E208',
  'name': 'A.G.M Rural College of Engineering and Technology-Varur, Hubballi',
  'location': 'HUBBALLI',
  'website': 'https://agmrcet.com/'},
 {'code': 'E209',
  'name': 'Aditya College of Engineering and Technology-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://adityaeducation.org.in/'},
 {'code': 'E211',
  'name': 'East West College of Engineering-Yelahanka, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://ewce.edu.in/'},
 {'code': 'E212',
  'name': 'Seshadripuram Institute of Technology-Kadakola Industrial Area , Mysuru',
  'location': 'Mysuru',
  'website': 'https://sitmysore.edu.in/'},
 {'code': 'E214',
  'name': 'Sri Siddhartha School of Engineering-Near Kyathsandra Toll Gate,Tumakuru',
  'location': 'TUMAKURU',
  'website': 'https://ssahe.edu.in/ssit/'},
 {'code': 'E215',
  'name': 'Cauvery College of Engineering -KBL Layout, Mysuru',
  'location': 'MYSURU',
  'website': 'https://cauveryengineering.edu.in/'},
 {'code': 'E216',
  'name': 'New Ebenezer Institute of Technology-Kothanur, Bengaluru',
  'location': 'BENGALURU',
  'website': 'https://neit.edu.in/'},
    {'code': 'E217',
     'name': 'Harsha Institute of Technology-Nelamangala Taluk, Bangalore Rural',
     'location': 'BENGALURU RURAL',
     'website': 'https://harshait.edu.in/'},
    {'code': 'E018', 'name': 'Bangalore College of Engineering and Technology', 'location': 'BENGALURU', 'website': ''},
    {'code': 'E057', 'name': 'H.M.S Institute of Technology', 'location': 'TUMAKURU', 'website': ''},
    {'code': 'E072', 'name': 'K.L.E Institute of Technology', 'location': 'HUBBALLI', 'website': ''},
    {'code': 'E210', 'name': 'Impact College of Engineering and Applied Sciences', 'location': 'BENGALURU', 'website': ''}
]

architecture_colleges = [{'code': 'E002',
  'name': "Acharya's NRV School of Architecture",
  'location': 'BENGALURU',
  'website': 'https://www.anrvsa.ac.in/'},
 {'code': 'E008', 'name': 'Angadi School of Architecture', 'location': 'BELAGAVI', 'website': 'https://asabgm.org/'},
 {'code': 'E016',
  'name': 'KLE Technological University (Formerly known as BVBCET)',
  'location': 'HUBBALI',
  'website': 'https://www.kletech.ac.in'},
 {'code': 'E026',
  'name': "BLDEA's V.P. Dr. P.G. Halakatti College of Engineering & Technology",
  'location': 'VIJAYAPURA',
  'website': 'https://www.bldeacet.ac.in'},
 {'code': 'E029', 'name': 'BMS School of Architecture', 'location': 'BENGALURU', 'website': 'https://www.bmssa.ac.in/'},
 {'code': 'E039',
  'name': 'Dayananda Sagar Academy of Technology & Management',
  'location': 'BENGALURU',
  'website': 'https://dsatm.edu.in'},
 {'code': 'E054',
  'name': 'GSSS School of Architecture for Women',
  'location': 'MYSURU',
  'website': 'https://gsss-soaw.ac.in/'},
 {'code': 'E073', 'name': 'KLS Gogte Institute of Technology', 'location': 'BELAGAVI', 'website': 'https://git.edu/'},
 {'code': 'E077',
  'name': 'M.S. Ramaiah Institute of Technology',
  'location': 'BENGALURU',
  'website': 'https://www.msrit.edu/'},
 {'code': 'E125',
  'name': 'Siddaganga Institute of Technology',
  'location': 'TUMAKURU',
  'website': 'https://www.sit.ac.in'},
 {'code': 'E138',
  'name': 'Srinivas Institute of Technology',
  'location': 'MANGALURU',
  'website': 'https://www.sitmangalore.in'},
 {'code': 'E163',
  'name': 'SJB School of Architecture & Planning',
  'location': 'BENGALURU',
  'website': 'https://www.sjbcnp.edu.in/'},
 {'code': 'E164', 'name': 'Reva University', 'location': 'BENGALURU', 'website': 'https://www.reva.edu.in/'},
 {'code': 'E168', 'name': 'Mysore School of Architecture', 'location': 'MYSURU', 'website': 'https://msamysore.in/'},
 {'code': 'E169', 'name': 'R.R School Of Architecture', 'location': 'BENGALURU', 'website': 'https://rrsa.edu.in/'},
 {'code': 'E175',
  'name': 'Gopalan School of Architecture and Planning',
  'location': 'BENGALURU',
  'website': 'https://www.gopalanschoolofarchitecture.com/'},
 {'code': 'E176', 'name': 'R V College of Architecture', 'location': 'BENGALURU', 'website': 'https://rvca.edu.in/'},
 {'code': 'E178',
  'name': 'Wadiyar Centre for Architecture',
  'location': 'MYSURU',
  'website': 'https://wadiyararchitecture.org/'},
 {'code': 'E181',
  'name': "Beary's Enviro-Architecture Design School",
  'location': 'MANGALURU',
  'website': 'https://beads.in/'},
 {'code': 'E187', 'name': 'CMR University', 'location': 'BENGALURU', 'website': 'https://www.cmr.edu.in/'},
 {'code': 'E189',
  'name': 'BMS College of Architecture, Design & Planning',
  'location': 'BENGALURU',
  'website': 'https://www.bmsca.org/'},
 {'code': 'E191',
  'name': 'Sir M V School Of Architecture',
  'location': 'BENGALURU',
  'website': 'https://www.sirmvsa.edu.in/'},
 {'code': 'E193',
  'name': 'Dayananda Sagar College of Architecture',
  'location': 'BENGALURU',
  'website': 'https://www.dscearch.edu.in/'},
 {'code': 'E213',
  'name': 'Poojya Dr. Shivakumar Swamiji School of Architecture',
  'location': 'TUMAKURU',
  'website': 'https://www.pdsssa.edu.in/'}]


