from backend.app import app
from flask import render_template, request
from backend.prediction import predict_colleges

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/exam-details')
def exam_details():
    return render_template('exam_details.html')

@app.route('/colleges')
def colleges():
    colleges_list = [
        {"code": "E001", "name": "Acharya Institute of Technology- Soladevanahalli, Bengaluru", "location": "BENGALURU"},
        {"code": "E003", "name": "A.C.S. College of Engineering Kambipura -(Mysore Road), Bengaluru", "location": "BENGALURU"},
        {"code": "E004", "name": "Adichunchanagiri Institute Of Technology-Jyothi Nagara, Chikkamagaluru", "location": "CHIKAMAGALURU"},
        {"code": "E005", "name": "Akash Institute of Engineering and Technology-Devanahalli, Bengaluru Rural", "location": "BENGALURU RURAL"},
        {"code": "E006", "name": "Alva's Institute of Engineering & Technology-Moodbidri, Mangaluru", "location": "MANGALURU"},
        {"code": "E007", "name": "AMC Engineering College-Bannerghatta Rd, Bengaluru", "location": "BENGALURU"},
        {"code": "E009", "name": "Angadi Institute of Technology and Management-Savagaon Road, Belagavi", "location": "BELAGAVI"},
        {"code": "E011", "name": "APS College of Engineering-Kanakapura Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E012", "name": "Atria Institute of Technology-Hebbal, Bengaluru", "location": "BENGALURU"},
        {"code": "E013", "name": "Akshaya Institute of Technology-Koratagere Road, Tumakuru", "location": "TUMAKURU"},
        {"code": "E014", "name": "Anuvartik Mirji Bharatesh Institute of Technology-Shindholli Cross, Belagavi", "location": "BELAGAVI"},
        {"code": "E015", "name": "B.N.M. Institute of Technology-Banashankari, Bengaluru", "location": "BENGALURU"},
        {"code": "E016", "name": "KLE Technological University (Formerly known as BVBCET)-Vidyanagar, Hubbali", "location": "HUBBALLI"},
        {"code": "E017", "name": "Ballari Institute of Technology & Management-Near Allipura, Ballari", "location": "BALLARI"},
        {"code": "E019", "name": "Bangalore Institute of Technology-V V Puram, Bengaluru", "location": "BENGALURU"},
        {"code": "E020", "name": "Bangalore Technological Institute-Chikkanayakanahalli Dinne, Bengaluru", "location": "BENGALURU"},
        {"code": "E021", "name": "Bapuji Institute of Engineering & Technology- Shamanur Road, Davangere", "location": "DAVANGERE"},
        {"code": "E023", "name": "Basavakalyan Engineering College-NH9 Basavakalyan, Bidar", "location": "BIDAR"},
        {"code": "E024", "name": "Basaveshwar Engineering College-Vidyanagar, Bagalkot", "location": "BAGALKOT"},
        {"code": "E026", "name": "BLDEA\"s V.P. Dr. P.G. Halakatti College of Engineering & Technology,Ashram Road, Vijayapura", "location": "VIJAYAPURA"},
        {"code": "E027", "name": "BMS College of Engineering-Basavanagudi, Bengaluru", "location": "BENGALURU"},
        {"code": "E028", "name": "BMS Institute of Technology & Management-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E030", "name": "Brindavan College of Engineering-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E032", "name": "C.M.R. Institute of Technology-Brookefield, Bengaluru", "location": "BENGALURU"},
        {"code": "E033", "name": "Cambridge Institute of Technology, K R Puram, Bengaluru", "location": "BENGALURU"},
        {"code": "E035", "name": "Channabasaveshwara Institute of Technology-Gubbi, Tumakuru", "location": "TUMAKURU"},
        {"code": "E036", "name": "Chanakya University-Devanahalli,Bengaluru Rural", "location": "BENGALURU RURAL"},
        {"code": "E037", "name": "City Engineering College-Doddakalasandra, Bengaluru", "location": "BENGALURU"},
        {"code": "E038", "name": "Coorg Institute of Technology-Ponnampet, South Kodagu", "location": "SOUTH KODAGU"},
        {"code": "E039", "name": "Dayananda Sagar Academy of Technology & Management-Kanakapura Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E040", "name": "Dayananda Sagar College of Engineering-Kumaraswamy Layout, Bengaluru", "location": "BENGALURU"},
        {"code": "E041", "name": "DON BOSCO Institute of Technology-Kumbalgodu, Bengaluru", "location": "BENGALURU"},
        {"code": "E042", "name": "Dr. Ambedkar Institute of Technology-Malathahalli, Bengaluru", "location": "BENGALURU"},
        {"code": "E043", "name": "Yenepoya Institute of Technology (formerly known as Dr. M V Shetty Institute of Technology)-Moodbidri, Mangaluru", "location": "MANGALURU"},
        {"code": "E044", "name": "Dr.Shri Shri Shivakumara Mahaswamy College of Engineering-Nelamangala, Bengaluru Rural", "location": "BENGALURU RURAL"},
        {"code": "E045", "name": "Dr H N National College Of Engineering - Jayanagar Bengaluru", "location": "BENGALURU"},
        {"code": "E046", "name": "East Point College of Engineering and Technology-Avalahalli, Bengaluru", "location": "BENGALURU"},
        {"code": "E048", "name": "East West Institute of Technology-BEL Layout, Bengaluru", "location": "BENGALURU"},
        {"code": "E049", "name": "Garden City University-Old Madras Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E050", "name": "Global Academy of Technology-Rajarajeshwari Nagar, Bengaluru", "location": "BENGALURU"},
        {"code": "E051", "name": "GM Institute of Technology-P B Road, Davangere", "location": "DAVANGERE"},
        {"code": "E053", "name": "Gopalan College of Engineering And Management- Whitefield, Bengaluru", "location": "BENGALURU"},
        {"code": "E055", "name": "GSSS Institute of Engineering and Technology for Women-Metagalli, Mysuru", "location": "MYSURU"},
        {"code": "E056", "name": "H.K.E.Society's P.D.A. College of Engineering-Aiwan E Shahi area, Kalaburgi", "location": "KALABURGI"},
        {"code": "E058", "name": "Sri Jayachamarajendra College of Engineering (constituent college of JSS Science and Technology University)-Manasagangothri, Mysuru", "location": "MYSURU"},
        {"code": "E059", "name": "Jawaharlal Nehru New College of Engineering (JNNCE)-Swalanga Road, Shivamogga", "location": "SHIVAMOGGA"},
        {"code": "E060", "name": "JSS Academy of Technical Education-Kengeri Main Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E061", "name": "JSS Science & Technology University-Mysuru", "location": "MYSURU"},
        {"code": "E062", "name": "Jain College of Engineering-T.S Nagar, Belagavi", "location": "BELAGAVI"},
        {"code": "E063", "name": "Jnana Vikas Institute of Technology-Bidadi, Ramnagar Taluk, Bengaluru Rural", "location": "BENGALURU RURAL"},
        {"code": "E064", "name": "Jain College Of Engineering & Research-Udyambag, Belagavi", "location": "BELAGAVI"},
        {"code": "E065", "name": "KLE Technological University (Formerly called as KLE Dr. M.S. sheshgiri college of Engineering and Technology)-Udyambag, Belagavi", "location": "BELAGAVI"},
        {"code": "E066", "name": "KLE College of Engineering and Technology, Chikodi Dist., Belagavi", "location": "BELAGAVI"},
        {"code": "E067", "name": "K.S School of Engineering And Management-Off Kanakapura Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E068", "name": "K.S. Institute of Technology-Kanakapura Main Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E069", "name": "KVG College Of Engineering-Sullia, Dakshina Kannada", "location": "DAKSHINA KANNADA"},
        {"code": "E070", "name": "Kalpataru Institute of Technology-B H Road, Tiptur", "location": "TIPTUR"},
        {"code": "E071", "name": "Karavali Institute of Technology-Kottara, Mangaluru", "location": "MANGALURU"},
        {"code": "E073", "name": "KLS Gogte Institute of Technology-Udyambag, Belagavi", "location": "BELAGAVI"},
        {"code": "E074", "name": "KLS's. Vishwanathrao Deshpande Institute of Technology-Dandeli Road, Haliyal", "location": "HALIYAL"},
        {"code": "E075", "name": "K. N. S. INSTITUTE OF TECHNOLOGY-Yelahanka,Bengaluru", "location": "BENGALURU"},
        {"code": "E076", "name": "M.S. Engineering College-Sadahalli, Bengaluru", "location": "BENGALURU"},
        {"code": "E077", "name": "M.S. Ramaiah Institute of Technology-MSR Nagar, Bengaluru", "location": "BENGALURU"},
        {"code": "E078", "name": "Maharaja Institute of Technology-Belawadi, Mandya", "location": "MANDYA"},
        {"code": "E079", "name": "Malnad College of Engineering-Rangoli Halla, Hassan", "location": "HASSAN"},
        {"code": "E080", "name": "Mangalore Institute of Technology & Engineering-Moodbidri, Mangaluru", "location": "MANGALURU"},
        {"code": "E081", "name": "Moodalakatte Institute of Technology-Moodalakatte, Kundapura", "location": "KUNDAPURA"},
        {"code": "E082", "name": "Maharaja Institute of Technology-Thandavapura, Mysuru", "location": "MYSURU"},
        {"code": "E083", "name": "Mysuru Royal Institute of Technology-Palahallli, Mandya District", "location": "MANDYA"},
        {"code": "E084", "name": "Nagarjuna College of Engineering & Technology-Devanahalli Bengaluru", "location": "BENGALURU"},
        {"code": "E085", "name": "The National Institute of Engineering, North Campus-Koorgalli, Mysuru", "location": "MYSURU"},
        {"code": "E088", "name": "Navodaya Institute of Technology-Bijangera, Raichur", "location": "RAICHUR"},
        {"code": "E089", "name": "P.E.S.College of Engineering-PES College Road, Mandya", "location": "MANDYA"},
        {"code": "E090", "name": "PES Institute of Technology & Management, Shivamogga", "location": "SHIVAMOGGA"},
        {"code": "E094", "name": "Proudhadevaraya Institute of Technology-TB Dam Road, Hosapete", "location": "HOSAPETE"},
        {"code": "E095", "name": "R V College of Engineering-Mysore Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E096", "name": "R.L. Jalappa Institute of Technology-Kodigehalli, Doddaballapur", "location": "DODDABALLAPUR"},
        {"code": "E097", "name": "R.R. Institute of Technology-Chikkabanavara, Bengaluru", "location": "BENGALURU"},
        {"code": "E098", "name": "R.T.E. Society's Rural Engineering College-Hulkoti, Gadag", "location": "GADAG"},
        {"code": "E099", "name": "Raja Rajeswari College of Engineering-Kumbalgodu, Bengaluru", "location": "BENGALURU"},
        {"code": "E100", "name": "Rajeev Institute of Technology-BM Bypass Road, Hassan", "location": "HASSAN"},
        {"code": "E101", "name": "Rajiv Gandhi Institute of Technology, R T Nagar Post, Bengaluru", "location": "BENGALURU"},
        {"code": "E102", "name": "Rao Bahadur Y Mahabaleswarappa Engineering College-Cantonment, Ballari", "location": "Ballari"},
        {"code": "E104", "name": "RNS Institute of Technology-R R Nagar Post, Bengaluru", "location": "BENGALURU"},
        {"code": "E105", "name": "Bheemanna Khandre Institute of Technology-Bhalki, Bidar", "location": "BIDAR"},
        {"code": "E107", "name": "SJB Institute of Technology-Kengeri, Bengaluru", "location": "BENGALURU"},
        {"code": "E108", "name": "S J C Institute of Technology-BB Road, Chikkaballapur", "location": "CHIKBALLAPUR"},
        {"code": "E109", "name": "S.E.A. College of Engineering & Technology-K R Puram, Bengaluru", "location": "BENGALURU"},
        {"code": "E110", "name": "SSET's S.G. Balekundri Institute of Technology-Shivabasava Nagar, Belagavi", "location": "BELAGAVI"},
        {"code": "E111", "name": "Hirasugar Institute of Technology- Nidasoshi,Belagavi", "location": "NIDASOSHI"},
        {"code": "E112", "name": "Sahyadri College of Engineering and Management-Adyar, Mangaluru", "location": "MANGALURU"},
        {"code": "E113", "name": "Sai Vidya Institute of Technology-Rajan Kunte, Bengaluru", "location": "BENGALURU"},
        {"code": "E114", "name": "Sambhram Institute of Technology-Jalahalli East, Bengaluru", "location": "BENGALURU"},
        {"code": "E116", "name": "SAPTHAGIRI NPS UNIVERSITY- Hesaraghatta Main Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E117", "name": "SDM College of Engineering & Technology, (Tulu Minority)-Kalaghatagi , Dharwad", "location": "DHARWAD"},
        {"code": "E118", "name": "SDM Institute of Technology, (Tulu Minority)-Ujjire, Dakshina Kannada", "location": "DAKSHINA KANNADA"},
        {"code": "E119", "name": "SECAB Institute of Engineering &Technology-Nauraspur-Bagalkot Road, Vijayapura", "location": "VIJAYAPURA"},
        {"code": "E121", "name": "Sri Sairam College of Engineering-Anekal, Bengaluru", "location": "BENGALURU"},
        {"code": "E122", "name": "Shree Devi Institute of Technology-Kenjar, Mangaluru", "location": "MANGALURU"},
        {"code": "E123", "name": "Shri Madhwa Vadiraja Institute of Technology & Management-Bantakal, Udupi", "location": "UDUPI"},
        {"code": "E124", "name": "Shridevi Institute of Engineering & Technology-Sira Road, Tumakuru", "location": "TUMAKURU"},
        {"code": "E125", "name": "Siddaganga Institute of Technology-B H Road, Tumakuru", "location": "TUMAKURU"},
        {"code": "E126", "name": "Sir M.Visvesvaraya Institute of Technology-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E127", "name": "S J M Institute of Technology - NH 4 Bye-pass, Chitradurga", "location": "CHITRADURGA"},
        {"code": "E128", "name": "Smt. Kamala and Sri Venkappa M. Agadi College of Engineering & Technology-Laxmeswar, Gadag", "location": "GADAG"},
        {"code": "E132", "name": "Sri Krishna Institute of Technology-Chikkabanavara, Bengaluru", "location": "BENGALURU"},
        {"code": "E136", "name": "Sri Taralabalu Jagadguru Institute of Technology-Haveri Dist., Ranebennur", "location": "RANEBENNUR"},
        {"code": "E137", "name": "Sri Venkateshwara College of Engineering-KIAL Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E138", "name": "Srinivas Institute of Technology-Hampankatta, Mangaluru", "location": "MANGALURU"},
        {"code": "E141", "name": "T. John Institute of Technology-Bannerghatta Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E142", "name": "The National Institute of Engineering, South Campus-Mananthavady Road, Mysuru", "location": "MYSURU"},
        {"code": "E143", "name": "Tontadarya College of Engineering-Mundaragi Road , Gadag", "location": "GADAG"},
        {"code": "E144", "name": "Veerappa Nisty Engineering College-Shorapur, Yadgir", "location": "YADGIR"},
        {"code": "E145", "name": "Vemana Institute of Technology-Koramangala, Bengaluru", "location": "BENGALURU"},
        {"code": "E146", "name": "Vidya Vikas Institute of Engineering & Technology-Alnahally, Mysuru", "location": "MYSURU"},
        {"code": "E147", "name": "Vidyavardhaka College of Engineering-Gokulam, Mysuru", "location": "MYSURU"},
        {"code": "E148", "name": "Vivekananda College of Engineering and Technology-Puttur, Dakshina Kannada", "location": "DAKSHINA KANNADA"},
        {"code": "E152", "name": "ATME College of Engineering-Bannur Road, Mysuru", "location": "MYSURU"},
        {"code": "E156", "name": "Jyothy Institute of Technology-Tathguni, Bengaluru", "location": "BENGALURU"},
        {"code": "E158", "name": "Shetty Institute of Technology -Shahabad Road,Kalaburagi", "location": "Kalaburagi"},
        {"code": "E159", "name": "Lingaraj Appa Engineering-Gornalli, Bidar", "location": "BIDAR"},
        {"code": "E161", "name": "Cambridge Institute of Technology (North Campus)-Kundana, Bengaluru", "location": "BENGALURU"},
        {"code": "E164", "name": "Reva University-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E165", "name": "Alliance College of Engineering & Design. Alliance University-Anekal, Bengaluru", "location": "BENGALURU"},
        {"code": "E171", "name": "GITAM (Deemed to be University)-Doddaballapur taluk, Bengaluru", "location": "BENGALURU"},
        {"code": "E172", "name": "Mysore College of Engineering and Management-Chikkahalli, Mysuru", "location": "MYSURU"},
        {"code": "E173", "name": "Presidency University-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E183", "name": "Jain Institute of Technology-Avaragere Village, Davangere", "location": "DAVANGERE"},
        {"code": "E187", "name": "CMR University-Bagalor Chagalatti, Bengaluru", "location": "BENGALURU"},
        {"code": "E191", "name": "Sir M V School Of Architecture-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E194", "name": "Jain College of Engineering and Technology-Unkal, Hubballi", "location": "HUBBALLI"},
        {"code": "E195", "name": "Navkis College of Engineering -Kandali NH75, Hassan", "location": "HASSAN"},
        {"code": "E197", "name": "M.S. Ramaiah University of Applied Sciences-MSR Nagar, Bengaluru", "location": "BENGALURU"},
        {"code": "E198", "name": "R V Institute of Technology and Management-J P Nagar, Bengaluru", "location": "BENGALURU"},
        {"code": "E199", "name": "Biluru Gurubasava Mahaswamiji Institute of Technology-Mudhol, Bagalkot", "location": "BAGALKOT"},
        {"code": "E201", "name": "G Madegowda Institute of Technology-Maddur, Mandya District", "location": "MANDYA"},
        {"code": "E202", "name": "C Byregowda Institute of Technology-Thoradevandahalli, Kolar", "location": "KOLAR"},
        {"code": "E203", "name": "Amruta Institute of Engineering and Management Science-Bidadi, Ramnagar Taluk, Bengaluru Rural", "location": "BENGALURU RURAL"},
        {"code": "E204", "name": "H.K.E. Society's Sir M. Visvesvaraya College of Engineering-Yermarus Camp, Raichur", "location": "RAICHUR"},
        {"code": "E205", "name": "Vijaya Vittala Institution of Technology-Kothanur, Bengaluru", "location": "BENGALURU"},
        {"code": "E206", "name": "Cauvery Institute Of Technology-Sundahalli, Mandya", "location": "MANDYA"},
        {"code": "E207", "name": "BGS College of Engineering and Technology-Mahalaxmipuram, Bengaluru", "location": "BENGALURU"},
        {"code": "E208", "name": "A.G.M Rural College of Engineering and Technology-Varur, Hubballi", "location": "HUBBALLI"},
        {"code": "E209", "name": "Aditya College of Engineering and Technology-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E211", "name": "East West College of Engineering-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E212", "name": "Seshadripuram Institute of Technology-Kadakola Industrial Area , Mysuru", "location": "Mysuru"},
        {"code": "E214", "name": "Sri Siddhartha School of Engineering-Near Kyathsandra Toll Gate,Tumakuru", "location": "TUMAKURU"},
        {"code": "E215", "name": "Cauvery College of Engineering -KBL Layout, Mysuru", "location": "MYSURU"},
        {"code": "E216", "name": "New Ebenezer Institute of Technology-Kothanur, Bengaluru", "location": "BENGALURU"},
        {"code": "E217", "name": "Harsha Institute of Technology-Nelamangala Taluk, Bangalore Rural", "location": "BENGALURU RURAL"}
    ]

    architecture_colleges = [
        {"code": "E002", "name": "Acharya's NRV School of Architecture-Soladevanahalli, Bengaluru", "location": "BENGALURU"},
        {"code": "E008", "name": "Angadi School of Architecture-Savagaon Road, Belagavi", "location": "BELAGAVI"},
        {"code": "E016", "name": "KLE Technological University (Formerly known as BVBCET)-Vidyanagar, Hubbali", "location": "HUBBALLI"},
        {"code": "E026", "name": "BLDEA\"s V.P. Dr. P.G. Halakatti College of Engineering & Technology-Ashram Road, Vijayapura", "location": "VIJAYAPURA"},
        {"code": "E029", "name": "BMS School of Architecture-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E039", "name": "Dayananda Sagar Academy of Technology & Management-Kanakapura Main Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E054", "name": "GSSS School of Architecture for Women-K R S Road, Mysuru", "location": "MYSURU"},
        {"code": "E073", "name": "KLS Gogte Institute of Technology-Udyambag, Belagavi", "location": "BELAGAVI"},
        {"code": "E077", "name": "M.S. Ramaiah Institute of Technology-MSR Nagar, Bengaluru", "location": "BENGALURU"},
        {"code": "E125", "name": "Siddaganga Institute of Technology-B H Road, Tumakuru", "location": "TUMAKURU"},
        {"code": "E138", "name": "Srinivas Institute of Technology-GHS Road, Mangaluru", "location": "MANGALURU"},
        {"code": "E163", "name": "SJB School of Architecture & Planning-Kengeri, Bengaluru", "location": "BENGALURU"},
        {"code": "E164", "name": "Reva University-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E168", "name": "Mysore School of Architecture-Lingambudi, Mysuru", "location": "MYSURU"},
        {"code": "E169", "name": "R.R School Of Architecture - Chikkabanavara, Bengaluru", "location": "Bengaluru"},
        {"code": "E175", "name": "Gopalan School of Architecture and Planning-Hoodi, Bengaluru", "location": "BENGALURU"},
        {"code": "E176", "name": "R V College of Architecture-Banashankari 6th Stage, Bengaluru", "location": "BENGALURU"},
        {"code": "E178", "name": "Wadiyar Centre for Architecture-Chamaraja Mohalla, Mysuru", "location": "MYSURU"},
        {"code": "E181", "name": "Beary's Enviro-Architecture Design School-Near Mangalore University, Mangaluru", "location": "MANGALURU"},
        {"code": "E187", "name": "CMR University-Bagalur-Chagalatti, Bengaluru", "location": "BENGALURU"},
        {"code": "E189", "name": "BMS College of Architecture, Design & Planning -Bull Temple Road, Bengaluru", "location": "BENGALURU"},
        {"code": "E191", "name": "Sir M V School Of Architecture-Yelahanka, Bengaluru", "location": "BENGALURU"},
        {"code": "E193", "name": "Dayananda Sagar College of Architecture-Kumaraswamy Layout, Bengaluru", "location": "BENGALURU"},
        {"code": "E213", "name": "Poojya Dr. Shivakumar Swamiji School of Architecture.", "location": "KALABURAGI"}
    ]
    return render_template('colleges.html', engineering_colleges=colleges_list, architecture_colleges=architecture_colleges)

@app.route('/predictor', methods=['GET', 'POST'])
def predictor():
    if request.method == 'POST':
        rank = request.form.get('rank')
        branch = request.form.getlist('branch')
        category = request.form.get('category')

        results = predict_colleges(rank, branch, category)

        return render_template('results.html', results=results, rank=rank, branch=branch)
    return render_template('predictor.html')

@app.route('/results')
def results():
    return render_template('results.html')

@app.route('/courses')
def courses():
    engineering_branches = [
        {"sl_no": 1, "name": "Aeronautical Engineering", "code": "AE"},
        {"sl_no": 2, "name": "Aerospace Engineering", "code": "AS"},
        {"sl_no": 3, "name": "Agriculture Engineering", "code": "AL"},
        {"sl_no": 4, "name": "Agricultural Engineering", "code": "AG"},
        {"sl_no": 5, "name": "Artificial Intelligence & Data Science", "code": "AD"},
        {"sl_no": 6, "name": "Artificial Intelligence & Machine Learning", "code": "AI"},
        {"sl_no": 7, "name": "Automation & Robotics Engineering", "code": "AR"},
        {"sl_no": 8, "name": "Automobile Engineering", "code": "AU"},
        {"sl_no": 9, "name": "Automotive Engineering", "code": "AVE"},
        {"sl_no": 10, "name": "Bachelor of Design", "code": "BD"},
        {"sl_no": 11, "name": "Bachelor of Urban & Regional Planning", "code": "BP"},
        {"sl_no": 12, "name": "Bachelor of Planning", "code": "BPL"},
        {"sl_no": 13, "name": "Bachelor of Design (Fashion Design)", "code": "BFD"},
        {"sl_no": 14, "name": "Bachelor of Design (Industrial Design)", "code": "BID"},
        {"sl_no": 15, "name": "Bachelor of Design (Lifestyle & Accessory Design)", "code": "BLD"},
        {"sl_no": 16, "name": "Bachelor of Design (Communication & Design)", "code": "BDC"},
        {"sl_no": 17, "name": "Bio Electronics Engineering", "code": "BEE"},
        {"sl_no": 18, "name": "Bio Medical Engineering", "code": "BM"},
        {"sl_no": 19, "name": "Biotechnology", "code": "BT"},
        {"sl_no": 20, "name": "Ceramic And Cement Technology", "code": "CC"},
        {"sl_no": 21, "name": "Chemical Engineering", "code": "CH"},
        {"sl_no": 22, "name": "Civil (Construction Engineering & Management)", "code": "CVC"},
        {"sl_no": 23, "name": "Civil Construction & Sustainability Engineering", "code": "CCS"},
        {"sl_no": 24, "name": "Civil Engineering", "code": "CV"},
        {"sl_no": 25, "name": "Civil Engineering (Kannada)", "code": "CK"},
        {"sl_no": 26, "name": "Civil Engineering (SC)", "code": "CVS"},
        {"sl_no": 27, "name": "Civil Engineering with Computer Application", "code": "CCA"},
        {"sl_no": 28, "name": "Computer & Communication Engineering", "code": "CM"},
        {"sl_no": 29, "name": "Computer Engineering", "code": "CE"},
        {"sl_no": 30, "name": "Computer Science", "code": "CR"},
        {"sl_no": 31, "name": "Computer Science & Business Systems", "code": "CB"},
        {"sl_no": 32, "name": "Computer Science & Design", "code": "CG"},
        {"sl_no": 33, "name": "Computer Science & Engineering", "code": "CS"},
        {"sl_no": 34, "name": "Computer Science & Engineering (AI & ML)", "code": "CI"},
        {"sl_no": 35, "name": "Computer Science & Engineering (AI)", "code": "CA"},
        {"sl_no": 36, "name": "Computer Science & Engineering (Block Chain)", "code": "CSB"},
        {"sl_no": 37, "name": "Computer Science & Engineering (Cyber Security)", "code": "CY"},
        {"sl_no": 38, "name": "Computer Science & Engineering (Data Science)", "code": "CD"},
        {"sl_no": 39, "name": "Computer Science & Engineering (IOT & Cyber Security Incl. Block Chain)", "code": "IC"},
        {"sl_no": 40, "name": "Computer Science & Engineering (IOT)", "code": "CO"},
        {"sl_no": 41, "name": "Computer Science & Engineering (Networks)", "code": "CNW"},
        {"sl_no": 42, "name": "Computer Science & Engineering (SC)", "code": "CSS"},
        {"sl_no": 43, "name": "Computer Science & Information Technology", "code": "CIT"},
        {"sl_no": 44, "name": "Computer Science & Technology", "code": "CN"},
        {"sl_no": 45, "name": "Computer Science & Technology (Big Data)", "code": "CBD"},
        {"sl_no": 46, "name": "Computer Science & Technology (DevOps)", "code": "CSD"},
        {"sl_no": 47, "name": "Construction Technology & Management", "code": "CT"},
        {"sl_no": 48, "name": "Cyber Security", "code": "CX"},
        {"sl_no": 49, "name": "Data Science", "code": "DS"},
        {"sl_no": 50, "name": "Electrical & Computer Engineering", "code": "ECE"},
        {"sl_no": 51, "name": "Electrical & Electronics Engineering", "code": "EE"},
        {"sl_no": 52, "name": "Electronics & Communication (Industry Integrated)", "code": "EII"},
        {"sl_no": 53, "name": "Electronics & Communication Engineering", "code": "EC"},
        {"sl_no": 54, "name": "Electronics & Communication Engineering (SC)", "code": "ECS"},
        {"sl_no": 55, "name": "Electronics & Computer Engineering", "code": "UE"},
        {"sl_no": 56, "name": "Electronics & Computer Science", "code": "ES"},
        {"sl_no": 57, "name": "Electronics & Instrumentation Engineering", "code": "EI"},
        {"sl_no": 58, "name": "Electronics & Telecommunication Engineering", "code": "ET"},
        {"sl_no": 59, "name": "Electronics Engg. (VLSI Design & Technology)", "code": "VL"},
        {"sl_no": 60, "name": "Electronics & Communication Engineering (VLSI Design & Technology)", "code": "ECV"},
        {"sl_no": 61, "name": "Energy Engineering", "code": "EN"},
        {"sl_no": 62, "name": "Industrial & Production Engineering", "code": "IP"},
        {"sl_no": 63, "name": "Industrial Engineering & Management", "code": "IM"},
        {"sl_no": 64, "name": "Information Science & Engineering", "code": "IS"},
        {"sl_no": 65, "name": "Information Science & Technology", "code": "IST"},
        {"sl_no": 66, "name": "Information Technology", "code": "INT"},
        {"sl_no": 67, "name": "Information Technology (AR / VR)", "code": "IAR"},
        {"sl_no": 68, "name": "Information Technology (Data Analytics)", "code": "IDA"},
        {"sl_no": 69, "name": "Instrumentation Technology", "code": "IT"},
        {"sl_no": 70, "name": "Marine Engineering", "code": "MR"},
        {"sl_no": 71, "name": "Mathematics & Computing", "code": "MAC"},
        {"sl_no": 72, "name": "Mechanical & Aerospace Engineering", "code": "MAE"},
        {"sl_no": 73, "name": "Mechanical Engineering", "code": "ME"},
        {"sl_no": 74, "name": "Mechanical Engineering (SC)", "code": "MES"},
        {"sl_no": 75, "name": "Mechatronics Engineering", "code": "MT"},
        {"sl_no": 76, "name": "Medical Electronics Engineering", "code": "MD"},
        {"sl_no": 77, "name": "Mining Engineering", "code": "MI"},
        {"sl_no": 78, "name": "Nano Technology", "code": "NT"},
        {"sl_no": 79, "name": "Petroleum Engineering", "code": "PTE"},
        {"sl_no": 80, "name": "Robotics", "code": "ROB"},
        {"sl_no": 81, "name": "Robotics & Artificial Intelligence", "code": "RI"},
        {"sl_no": 82, "name": "Robotics & Automation", "code": "RA"},
        {"sl_no": 83, "name": "Robotics & Mechatronics", "code": "ROM"},
        {"sl_no": 84, "name": "Smart Agritech", "code": "SA"},
        {"sl_no": 85, "name": "Telecommunication Engineering", "code": "TE"},
        {"sl_no": 86, "name": "Textile Technology", "code": "TX"},
        {"sl_no": 87, "name": "VLSI", "code": "VLS"},
        {"sl_no": 88, "name": "Computer Science & Engineering (Artificial Intelligence & Data Science)", "code": "CAD"}
    ]

    architecture_branches = [
        {"sl_no": 1, "name": "Bachelor of Architecture (B.Arch)", "code": "AT"},
        {"sl_no": 2, "name": "Bachelor of Urban & Regional Planning", "code": "BP"},
        {"sl_no": 3, "name": "Bachelor of Design", "code": "BD"},
        {"sl_no": 4, "name": "Bachelor of Design (Fashion Design)", "code": "BFD"},
        {"sl_no": 5, "name": "Bachelor of Design (Industrial Design)", "code": "BID"},
        {"sl_no": 6, "name": "Bachelor of Design (Lifestyle & Accessory Design)", "code": "BLD"},
        {"sl_no": 7, "name": "Bachelor of Design (Communication & Design)", "code": "BDC"},
        {"sl_no": 8, "name": "Bachelor of Planning", "code": "BPL"},
        {"sl_no": 9, "name": "B. Design (Interior Design)", "code": "BIN"}
    ]

    return render_template('courses.html', engineering_branches=engineering_branches, architecture_branches=architecture_branches)
